image: node:8.7.0
clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - git checkout master--
          - npm install
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD